# Generated by Django 5.2.17 on 2026-09-01 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastodon', '0003_managedvinylhubcommunityaccount_and_more'),
        ('users', '0018_managed_identity_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCommunityProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_handle', models.CharField(max_length=30, unique=True)),
                ('technical_email', models.EmailField(max_length=255)),
                ('display_seed', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('provisioned', 'Provisioned'), ('rejected', 'Rejected'), ('unknown', 'Unknown'), ('suspended', 'Suspended'), ('suspend_unknown', 'Suspend unknown'), ('deleting', 'Deleting'), ('delete_unknown', 'Delete unknown'), ('deleted', 'Deleted')], default='pending', max_length=24)),
                ('operation', models.CharField(choices=[('provision', 'Provision'), ('read', 'Read'), ('suspend', 'Suspend'), ('resume', 'Resume'), ('delete', 'Delete')], default='provision', max_length=16)),
                ('remote_user_id', models.CharField(blank=True, max_length=255)),
                ('remote_profile_url', models.URLField(blank=True, max_length=2048)),
                ('last_error_category', models.CharField(blank=True, max_length=40)),
                ('last_error_text', models.CharField(blank=True, max_length=500)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='managed_community_projection', to='users.managedidentitybinding')),
                ('managed_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_community_projection', to='mastodon.socialaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='managed_community_projection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'operation'], name='managed_comm_state_op')],
            },
        ),
    ]
