# Generated by Django 5.2.17 on 2026-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="catalog_languages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
