# Generated by Django 5.2.17 on 2026-09-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0028_alter_externalresource_id_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="core_catalog_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Core catalog reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                condition=models.Q(("core_catalog_ref__isnull", False)),
                fields=("core_catalog_ref",),
                name="unique_album_core_catalog_ref",
            ),
        ),
    ]
