# Generated by Django 5.2.17 on 2026-10-03 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0019_backfill_attachments"),
        ("users", "0021_alter_task_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardcoverImporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.task",),
        ),
    ]
