# Generated by Django 5.2.17 on 2026-09-07 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0020_twitterimporter"),
    ]

    operations = [
        migrations.CreateModel(
            name="MastodonImporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.baseimporter",),
        ),
    ]
