# Generated by Django 4.2.18 on 2025-01-27 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def merge_to(self, to_item: "Item | None"):
    if to_item is None:
        if self.merged_to_item is not None:
            self.merged_to_item = None
            self.save()
        return
    if to_item.pk == self.pk:
        return
        raise ValueError("cannot merge to self")
    if to_item.merged_to_item is not None:
        return
        raise ValueError("cannot merge to item which is merged to another item")
    if not isinstance(to_item, self.__class__):
        raise ValueError("cannot merge to item in a different model")
    self.merged_to_item = to_item
    self.save()
    for res in self.external_resources.all():
        res.item = to_item
        res.save()
    for edition in self.editions.all():
        edition.related_work = to_item
        edition.save()
    to_item.save()


def merge_works(apps, schema_editor):
    if getattr(settings, 'SKIP_WORK_MIGRATION', False):
        return
    Edition = apps.get_model("catalog", "Edition")
    Work = apps.get_model("catalog", "Work")
    for edition in Edition.objects.all():
        works = edition.works.all()
        if works.exists():
            if edition.related_work is None:
                related_work = works.first()
                if related_work.merged_to_item is not None:
                    related_work = related_work.merged_to_item
                edition.related_work = related_work
                edition.save()
            for work in works:
                if work.pk == edition.related_work.pk:
                    continue
                merge_to(work, edition.related_work)

def process_pending_trigger_events(apps, schema_editor):
    # Ensure all pending trigger events are processed
    schema_editor.connection.cursor().execute("SET CONSTRAINTS ALL IMMEDIATE")

class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_alter_model_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="related_work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_editions",
                to="catalog.work",
            ),
        ),
        migrations.RunPython(process_pending_trigger_events),
        migrations.RunPython(merge_works),
    ]
