# Generated by Django 5.2.17 on 2026-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastodon', '0002_socialaccount_ix_social_type_handle_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedVinylHubCommunityAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Managed VinylHub Community account',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mastodon.mastodonaccount',),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='type',
            field=models.CharField(choices=[('mastodon.blueskyaccount', 'bluesky account'), ('mastodon.emailaccount', 'email account'), ('mastodon.managedvinylhubcommunityaccount', 'Managed VinylHub Community account'), ('mastodon.mastodonaccount', 'mastodon account'), ('mastodon.threadsaccount', 'threads account')], db_index=True, max_length=255),
        ),
    ]
