# Generated by Django 3.2.19 on 2023-06-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastodon', '0002_add_api_domain_server_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosssiteuserinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mastodonapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
