# Generated by Django 5.2.17 on 2026-10-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0032_fanout_subject_document_alter_fanout_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="uri",
            field=models.CharField(
                blank=True, db_index=True, max_length=500, null=True
            ),
        ),
    ]
